### PR TITLE
Adding LLaVA-Phi-Mini-3

### PR DESCRIPTION
**Pull request by s-smits**
The model almost works, the chat template however is wrong. Maybe wait for an official update from HF for apply_chat_template?

### CODE REVIEW

**Comment by Blaizzy** [comment]
Awesome, great work!

You can try using the default chat template. Something like:

```python
tokenizer.chat_template = tokenizer.default_chat_template
```

**Comment by Blaizzy** [comment]
> Awesome, great work!
> 
> You can try using the default chat template. Something like:
> 
> ```python
> tokenizer.chat_template = tokenizer.default_chat_template
> ```

Actually they do have a chat template, check here: 

https://huggingface.co/xtuner/llava-phi-3-mini-hf/blob/main/tokenizer_config.json#L354

**Comment by Blaizzy** [comment]
> The model almost works, the chat template however is wrong. Maybe wait for an official update from HF for apply_chat_template?

What do you mean by the chat template is wrong?
Could you elaborate?

**Comment by s-smits** [comment]
Thank you!
The output is the following:
`These are two cats sleeping on a pink couch.<|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|><|end|>```
`
From my experience this normally is a chat template problem, where the model does not know when to stop. What do you think?

**Comment by Blaizzy** [comment]
> Thank you! The output is the following: `These are two cats sleeping on a pink couch.<|end|><|end|><|end|><|end|><|end|><|end|><|end|>... ` From my experience this normally is a chat template problem, where the model does not know when to stop. What do you think?

Hmm, the model is working fine. The problem exists because eos_token is different from the one used in the chat template.

If you patch the tokenizer it will work :)

```python
tokenizer.eos_token = "<|end|>"
```

**Comment by s-smits** [comment]
Tried two options:

Option 1
Add         
`self.tokenizer.eos_token = "<|end|>"
`
to language.LanguageModel __init__

Option 2
```
    model.language_model.tokenizer.eos_token = "<|end|>"
    model.language_model.tokenizer.pad_token = "<|end|>"

```
in llavaPhi.Model from_pretrained at the end before return model.

Unfortunately both did not work.

**Comment by Blaizzy** [comment]
Tokenizer is in the processor.

Llava type models usually have it setup this way `processor.tokenizer` while others, such as nanollava have it as the processor itself `processor`.

Check:

https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/utils.py#L714-L719

**Comment by s-smits** [comment]
Got it working with   
utils.py 714:723
```
    if image_processor is not None:
        prompt_tokens = mx.array(processor.encode(prompt))
        tokenizer = processor
    else:
        prompt_tokens = mx.array(processor.tokenizer.encode(prompt))
        tokenizer = processor.tokenizer
    
    if model.config.text_config.model_type == 'llama':
        processor.tokenizer.eos_token = "<|end|>"
        processor.tokenizer.pad_token = "<|end|>"

```
However, this also overrides the llava-1.5 model right? So I tried to add an extra condition, but I cannot  call model_type == 'llava':

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/air/Repositories/mlx-vlm/mlx_vlm/generate.py", line 95, in <module>
    main()
  File "/Users/air/Repositories/mlx-vlm/mlx_vlm/generate.py", line 82, in main
    generate(
  File "/Users/air/Repositories/mlx-vlm/mlx_vlm/utils.py", line 724, in generate
    print('model type',model.config.model_type)
AttributeError: 'ModelConfig' object has no attribute 'model_type'
```

```
{
--
  | "architectures": [
  | "LlavaForConditionalGeneration"
  | ],
  | "ignore_index": -100,
  | "image_token_index": 32038,
  | "model_type": "llava",
  | "pad_token_id": 32039,
  | "projector_hidden_act": "gelu",
  | "text_config": {
  | "architectures": [
  | "LlamaForCausalLM"
  | ],
  | "eos_token_id": 32000,
  | "hidden_size": 3072,
  | "intermediate_size": 8192,
  | "max_position_embeddings": 4096,
  | "model_type": "llama",
  | "original_max_position_embeddings": 4096,
  | "pad_token_id": 32000,
  | "rms_norm_eps": 1e-05,
  | "sliding_window": 2048,
  | "torch_dtype": "float16",
  | "vocab_size": 32064
  | },
  | "torch_dtype": "float16",
  | "transformers_version": "4.40.1",
  | "vision_config": {
  | "architectures": [
  | "CLIPVisionModel"
  | ],
  | "dropout": 0.0,
  | "hidden_size": 1024,
  | "image_size": 336,
  | "intermediate_size": 4096,
  | "model_type": "clip_vision_model",
  | "num_attention_heads": 16,
  | "num_hidden_layers": 24,
  | "patch_size": 14,
  | "projection_dim": 768,
  | "torch_dtype": "float32"
  | },
  | "vision_feature_layer": -2,
  | "vision_feature_select_strategy": "default"
  | }
```

If you know how to call the right component where model config main architecture == 'llama', could you implement this? Then we can merge.

**Comment by Blaizzy** [comment]
> Got it working with utils.py 714:723
> 
> ```
>     if image_processor is not None:
>         prompt_tokens = mx.array(processor.encode(prompt))
>         tokenizer = processor
>     else:
>         prompt_tokens = mx.array(processor.tokenizer.encode(prompt))
>         tokenizer = processor.tokenizer
>     
>     if model.config.text_config.model_type == 'llama':
>         processor.tokenizer.eos_token = "<|end|>"
>         processor.tokenizer.pad_token = "<|end|>"
> ```
> 

Great!

I would prefer if we patch the tokenizer directly and save it once we convert the model in the MLX hub :)

That way we don't have to add that extra logic here.

**Comment by Blaizzy** [comment]
Btw, I just added tests recently https://github.com/Blaizzy/mlx-vlm/pull/13.

**Comment by Blaizzy** [comment]
Please don't forget to rename the folder to `llavaPhi3`

**Comment by Blaizzy** [comment]
Closes #11

**Comment by Blaizzy** [comment]
Hey @s-smits,

Thank you very much for your contributions!

During my tests I found that this model uses the existing llava implementation. I will close this PR.

You can use the already pre-quantized model in the hub:
- https://huggingface.co/mlx-community/llava-phi-3-mini-4bit
- https://huggingface.co/mlx-community/llava-llama-3-8b-v1_1-4bit

**Comment by s-smits** [comment]
You're welcome. Due to other projects I couldn't finish it in time, thank you for converting it.

**Pull request closed without merging**
