### PR TITLE
Add support for Qwen2-VL

### PR DESCRIPTION
**Pull request by Blaizzy**

### CODE REVIEW

**Comment by MDR4356** [comment]
This isn't super relevant, but just thought I'd mention I'm excited for this. As I posted on Reddit recently:

```

> I'm an AI enthusiast and postconviction attorney looking to experiment with a local RAG setup for criminal case files. A typical file can be thought of as consisting of two main parts:
> 
> Official court record: filed documents (complaints, motions, administrative notices, etc.), document/photo exhibits from trials or hearings, and transcripts.
> 
> Everything else (basically the trial attorney's file which includes discovery material): might be handwritten notes, emails and correspondence with clients, private investigator reports, and discovery materials from the state (police reports, interview audio/video recordings, DNA reports, autopsy and crime scene photos, etc.).
> 
> The first part is much easier to convert to text and clean up (and pretty much the only thing I've tried analyzing/summarizing with local models. The second part is a very different animal, but something I'd like to start tackling.
> 
> I keep hearing about ColPali. Is this what I need? Any input is appreciated!

```
I would like to do something like this:
https://github.com/merveenoyan/smol-vision/blob/main/ColPali_%2B_Qwen2_VL.ipynb?t&utm_source=perplexity

Somehw figure out a way to investigate large collections of police reports and other discovery materials, many of which have tables, handwriting, etc. Thought ColPali + Qwen VL would be the way to go!

BTW I messaged you earlier on Twitter. Thanks again for working on this!

**Comment by Blaizzy** [comment]
@awni

**Comment by awni** [comment]
I'm slowly getting up to speed here. Just running this on your Qwen branch crashes right now:

```bash
python -m mlx_vlm.generate --model Qwen/Qwen2-VL-2B-Instruct --max-tokens 100 --temp 0.0
```

Error is:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/awnihannun/mlx-vlm/mlx_vlm/generate.py", line 85, in <module>
    main()
  File "/Users/awnihannun/mlx-vlm/mlx_vlm/generate.py", line 70, in main
    output = generate(
             ^^^^^^^^^
  File "/Users/awnihannun/mlx-vlm/mlx_vlm/utils.py", line 913, in generate
    prompt_tokens = mx.array(processor.tokenizer.encode(prompt))
                             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Qwen2TokenizerFast' object has no attribute 'tokenizer'. Did you mean: '_tokenizer'?
```

**Comment by awni** [comment]
@Blaizzy can you let me know the right way to test this model / how you have been testing it? It seems like it might be missing an ImageProcessor / I don't really get what's going on there. But right now it doesn't run with the command as it should..

**Comment by Blaizzy** [comment]
That's weird! It should run on you terminal. 

Some model use processor and some use a dedicate image processor. Qwen2-VL uses a processor.

The problem is the outputs themselves.

Screenshot 2024-09-27 at 9 49 40 AM

**Comment by Blaizzy** [comment]
> how you have been testing it?

Yes, I keep a notebook where I run all my tests. 

I test for closeness of results for each layer, module and the whole model. Additionally, to pin-point minor bugs I test if the vision or text features of transformers would work better if passed to the MLX version

Screenshot 2024-09-27 at 10 00 51 AM

**Comment by Blaizzy** [comment]
Here are some of the tests I ran.

```python
import torch
from transformers import Qwen2VLForConditionalGeneration
from PIL import Image
import requests
import torch
from torchvision import io
from typing import Dict
from transformers import AutoTokenizer, AutoProcessor
from transformers.image_utils import load_image
from mlx_vlm import load
import mlx.core as mx
from mlx_vlm.models.base import create_attention_mask
import numpy as np


# Load models
model_path = "Qwen/Qwen2-VL-2B-Instruct"
model = Qwen2VLForConditionalGeneration.from_pretrained(model_path)

model_mlx, _ = load(model_path) # skipping mlx processor because of detokenizer patch.
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct") 

# Image
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = load_image(url)

conversation = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
            },
            {"type": "text", "text": "What are these?"},
        ],
    }
]


# Preprocess the inputs
text_prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)
# Excepted output: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<|vision_start|><|image_pad|><|vision_end|>Describe this image.<|im_end|>\n<|im_start|>assistant\n'

inputs = processor(
    text=[text_prompt], images=[image], padding=True, return_tensors="pt"
)
```

# 1. Testing Vision tower
```python
## Patch embeddings
patch_embed = model.visual.patch_embed(inputs['pixel_values'])
patch_embed_mlx = model_mlx.vision_tower.patch_embed(mx.array(inputs['pixel_values']))

print(
    np.allclose(
        patch_embed.detach().numpy(),
        patch_embed_mlx,
        rtol=1e-3,
        atol=1e-3
    )
)

## Vision tower blocks
hidden_states = model.visual.blocks[0](patch_embed, torch.tensor(cu_seqlens), rot_pos_emb)
hidden_states_mlx = model_mlx.vision_tower.blocks[0](mx.array(patch_embed), mx.array(cu_seqlens), mx.array(rot_pos_emb))

np.allclose(np.array(hidden_states[0].detach().cpu()), hidden_states_mlx[0], rtol=1e-3, atol=1e-3)

## Vision tower merger
cu_seqlens = torch.repeat_interleave(
    inputs['image_grid_thw'][:, 1] * inputs['image_grid_thw'][:, 2], inputs['image_grid_thw'][:, 0]
).cumsum(dim=0, dtype=torch.int32)
cu_seqlens = F.pad(cu_seqlens, (1, 0), value=0)

merger = model.visual.merger(hidden_states)
merger_mlx = model_mlx.vision_tower.merger(hidden_states_mlx)

np.allclose(np.array(merger.detach().cpu()), merger_mlx, rtol=1e-3, atol=1e-3)

## Whole vision tower
vision_mlx = model_mlx.vision_tower(mx.array(inputs['pixel_values']), np.array([[1, 34, 46]]), output_hidden_states=False)

vision_output = None
def hook_fn(module, input, output):
    global vision_output
    if isinstance(module, type(model.visual)):
        print(f"Module: {type(module).__name__}")
        print(f"Input shape: {input[0].shape}")
        print(f"Output shape: {output.shape}")
        vision_output = output.detach().cpu().numpy()

hook_handle = model.visual.register_forward_hook(hook_fn)

output_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids = [
    output_ids[len(input_ids) :]
    for input_ids, output_ids in zip(inputs.input_ids, output_ids)
]
output_text = processor.batch_decode(
    generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=True
)
print(output_text)
hook_handle.remove()


print(np.allclose(vision_output, vision_mlx, rtol=1e-3, atol=1e-3))
```


# Testing Language model
```python
emb = model.model.embed_tokens(inputs['input_ids'])
emb_mlx = model_mlx.language_model.model.embed_tokens(mx.array(inputs['input_ids']))

## Language model blocks
hidden_states = model.visual.blocks[0](patch_embed, torch.tensor(cu_seqlens), rot_pos_emb)
hidden_states_mlx = model_mlx.vision_tower.blocks[0](mx.array(patch_embed), mx.array(cu_seqlens), mx.array(rot_pos_emb))

np.allclose(np.array(hidden_states[0].detach().cpu()), hidden_states_mlx[0], rtol=1e-3, atol=1e-3)

## Language model blocks / layers
kv_seq_len = 416
position_ids = mx.arange(0, kv_seq_len)

position_ids = mx.expand_dims(position_ids, axis=0)
position_ids = np.tile(position_ids, (3, 1, 1))

language_layer = model.model.layers[0](emb, position_ids=position_ids)[0]
mask = create_attention_mask(emb_mlx, None)
language_layer_mlx = model_mlx.language_model.model.layers[0]

print(np.allclose(np.array(language_layer.detach().cpu()), language_layer_mlx, rtol=1e-3, atol=1e-3))
```

# 3. Inference using transformers vision features

## MLX model
```python
from mlx_vlm.models.base import KVCache
def _merge_input_ids_with_image_features(
        image_features, inputs_embeds, input_ids
    ):
        image_token_index = 151655

        # Positions of <image> tokens in input_ids, assuming batch size is 1
        image_positions = input_ids == image_token_index
        inputs_embeds = np.array(inputs_embeds.astype(mx.float32))
        inputs_embeds[image_positions] = image_features

        # TODO: Add video features

        return mx.array(inputs_embeds)

def sample(logits: mx.array):
    logit_bias = None
    temp = 0.0
    top_p = 1.0
    if logit_bias:
        indices = mx.array(list(logit_bias.keys()))
        values = mx.array(list(logit_bias.values()))
        logits[:, indices] += values
    logprobs = logits - mx.logsumexp(logits)

    if temp == 0:
        token = mx.argmax(logits, axis=-1)
    else:
        if top_p > 0 and top_p < 1.0:
            token = top_p_sampling(logits, top_p, temp)
        else:
            token = mx.random.categorical(logits * (1 / temp))

    return token, logprobs

if hasattr(model_mlx.language_model, "make_cache"):
    cache = model_mlx.language_model.make_cache()
else:
    kv_heads = (
        [model_mlx.language_model.n_kv_heads] * len(model_mlx.language_model.layers)
        if isinstance(model_mlx.language_model.n_kv_heads, int)
        else model_mlx.language_model.n_kv_heads
    )
    cache = [KVCache(model_mlx.language_model.head_dim, n) for n in kv_heads]

def _step(y):
    logits = model_mlx.language_model(y[None], cache=cache, mask=mask)
    logits = logits[:, -1, :]
    y, logprobs = sample(logits)

    return y, logprobs.squeeze(0)

inputs_embeds = mx.array(vision_output[None, :])
embeds = model_mlx.language_model.model.embed_tokens(mx.array(inputs['input_ids']))
inputs_embeds = _merge_input_ids_with_image_features(inputs_embeds, embeds, mx.array(inputs['input_ids']))

mask = None
logits = model_mlx.language_model(inputs=None, mask=None, inputs_embeds=inputs_embeds)
logits = logits[:, -1, :]
y, logprobs = sample(logits)
mx.async_eval(y)
n = 100
for i in range(n):
    next_y, next_logprobs = _step(y)
    mx.async_eval(next_y)
    print(processor.decode(np.array(y.item())), end=" ")
    y, logprobs = next_y, next_logprobs
```


## Transformers
```python
def manual_generate(input_embeds, max_length=10, temperature=0.7):
    model.eval()

    with torch.no_grad():
        # Initialize the sequence with the input embeddings
        current_embeds = input_embeds

        generated_token_ids = []

        for _ in range(max_length):
            # Forward pass
            outputs = model(inputs_embeds=current_embeds)

            # Get the next token probabilities
            next_token_logits = outputs.logits[:, -1, :] / temperature

            # Apply softmax to get probabilities
            next_token_probs = torch.softmax(next_token_logits, dim=-1)

            # Sample the next token
            next_token = torch.multinomial(next_token_probs, num_samples=1)

            # Add the new token to our generated sequence
            generated_token_ids.append(next_token.item())

            # Stop if we generate an EOS token
            if next_token.item() == processor.tokenizer.eos_token_id:
                break

            # Get the embedding for the new token
            next_token_embed = model.get_input_embeddings()(next_token)

            # Add the new token embedding to our sequence
            current_embeds = torch.cat([current_embeds, next_token_embed], dim=1)

    # Decode the generated token IDs
    generated_text = processor.tokenizer.decode(generated_token_ids, skip_special_tokens=True)
    return generated_text

manual_generate(torch.from_numpy(np.array(inputs_embeds)))
```

**Comment by Blaizzy** [comment]
> Just running this on your Qwen branch crashes right now:

@awni  found your error. Just update to the latest transformers and it should work.

```
pip install -U transformers
```

**Comment by awni** [comment]
> @awni found your error it's caused by transfomers v4.39.3. Just update to the latest transformers and it should work.

Thanks 🤦  I should have tried that first :). Also seems like the LM is working but the vision model is having issues. That's where you're at right?

```
The image appears to be a distorted or glitched version of a photograph or digital image. The pattern of lines and the overall texture suggest it might be a result of digital corruption or a digital filter applied to the original image. The specific details of the image are difficult to discern due to the distortion.
```

**Comment by Blaizzy** [comment]
>  Also seems like the LM is working but the vision model is having issues. That's where you're at right?

Yes, that's what I initially thought. 

Althought the LM responds correctly even to just text input. I'm not 100% sure the LM works properly because when I pass the transformers vision features to the MLX language model it's outputs are different from the transformers.

Input: `What are these?`
Image URL: `http://images.cocodataset.org/val2017/000000039769.jpg`
Vision features source: `Transformers`

MLX language model
`
These   1 0 0 0  square  feet  of  space  is  the  perfect  size  for  a  small  apartment ,  a  studio  apartment ,  or  a  small  home  office .  The  floor  plan  is  open  and  airy ,  with  a  large  living  room ,  a  kitchen ,  and  a  dining  area . 
`

Transformers language model
`
These are two cats.
`

**Comment by awni** [comment]
```python -m mlx_vlm.generate --model Qwen/Qwen2-VL-2B-Instruct --max-tokens 100 --temp 0.0```

```
These are two cats.
```


Fix in `PatchEmbed` `__call__`:

```python
    def __call__(self, hidden_states: mx.array) -> mx.array:
        hidden_states = hidden_states.reshape(
            -1,
            self.in_channels,
            self.temporal_patch_size,
            self.patch_size,
            self.patch_size,
        ).moveaxis(1, 4)
        hidden_states = self.proj(hidden_states)
        hidden_states = hidden_states.reshape(-1, self.embed_dim)
        return hidden_states
```

**Comment by awni** [comment]
Also not sure why you are converting to numpy in `def rot_pos_emb`. I would just do the whole thing in MLX and avoid the graph evaluation. It's also simpler.. 

```python
        rotary_pos_emb = rotary_pos_emb_full[pos_ids]

        # flatten
        return rotary_pos_emb.reshape(pos_ids.shape[0], -1)
```

**Comment by Blaizzy** [comment]
> Also not sure why you are converting to numpy in def rot_pos_emb. I would just do the whole thing in MLX and avoid the graph evaluation. It's also simpler..

I do it for debugguing because the numpy code looks closer to torch and also the MLX version is not always clear when I start.

**Comment by Blaizzy** [comment]
@awni could you explain why it works when I do .moveaxis(1, 4) instead of just chaging when reshaping?

**Comment by awni** [comment]
A reshape doesn’t change the underlying data order that the embedding module expects. You have to reshape to the right shape and the put the dimensions in the right place.

**Comment by Blaizzy** [comment]
Also, is there a better way to do cumsum?

This works: 
`cu_seqlens = mx.array(np.cumsum(cu_seqlens, dtype=np.int32))`

I tried the MLX cumsum but I get an error.

`cu_seqlens = mx.array(mx.cumsum(cu_seqlens))`

Screenshot 2024-09-27 at 6 40 13 PM
rs.

**Comment by Blaizzy** [comment]
> A reshape doesn’t change the underlying data order that the embedding module expects. You have to reshape to the right shape and the put the dimensions in the right place.

A bit of a basic question.

What's the difference between this:

```
 hidden_states = hidden_states.reshape(
            -1,
            self.temporal_patch_size,
            self.patch_size,
            self.patch_size,
            self.in_channels,
        )
```

and this: 
```
        hidden_states = hidden_states.reshape(
            -1,
            self.in_channels,
            self.temporal_patch_size,
            self.patch_size,
            self.patch_size,
        ).moveaxis(1, 4)

```

If the final resulting tensor has the same shape. Why is it that one produces a good result and the other doesn't?

**Comment by Blaizzy** [comment]
@awni There is another issue with the `apply_multimodal_rotary_pos_emb`.
I can't split it using MLX .split() as explained here: https://x.com/Prince_Canuma/status/1839350247887364211
So, I adapted it this way for now.
```python
def apply_multimodal_rotary_pos_emb(
    q, k, cos, sin, position_ids, mrope_section, unsqueeze_dim=1
):
    """
    Applies Rotary Position Embedding with Multimodal Sections to the query and key tensors.

    Args:
        q (mx.array): The query tensor.
        k (mx.array): The key tensor.
        cos (mx.array): The cosine part of the rotary embedding.
        sin (mx.array): The sine part of the rotary embedding.
        mrope_section (List[int]): Multimodal rope section for channel dimension of temporal, height and width.
        unsqueeze_dim (int, optional): Dimension to unsqueeze. Defaults to 1.

    Returns:
        tuple(mx.array): The rotated query and key tensors.
    """

    mrope_section = mrope_section * 2

    position_ids = position_ids.tolist()
    cos = cos[position_ids]
    sin = sin[position_ids]
    cos = torch.from_numpy(np.array(cos))
    sin = torch.from_numpy(np.array(sin))
    cos = torch.cat(
        [m[i % 3] for i, m in enumerate(cos.split(mrope_section, dim=-1))], dim=-1
    ).unsqueeze(unsqueeze_dim)
    sin = torch.cat(
        [m[i % 3] for i, m in enumerate(sin.split(mrope_section, dim=-1))], dim=-1
    ).unsqueeze(unsqueeze_dim)

    q = torch.from_numpy(np.array(q))
    k = torch.from_numpy(np.array(k))
    # Apply rotary embedding
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)

    return mx.array(q_embed), mx.array(k_embed)
```

**Comment by awni** [comment]
> If the final resulting tensor has the same shape. Why is it that one produces a good result and the other doesn't

The order you interpret the unerlying data matters. reshape (in most array frameworks like numpy, jax, pytorch, MLX, etc)  assumes the data is row-contiguous. So when you reshape it you get a row-contiguous view of the data.

For example:

```python
x = np.array([1,2,3,4, 5, 6]).reshape(2, 3)
print(x.T)
```

The above is very different from:

```python
x = np.array([1,2,3,4,5,6]).reshape(3, 2)
print(x0
```

even though the resulting shapes are the same.

**Comment by awni** [comment]
> So, I adapted it this way for now.

Oof using PyTorch in MLX code makes me a little sad 😢  .. you shouldn't need that. `mx.split` works like `np.split` which are both different than `torch.split`.

In short you can do `mrope_section = np.cumsum(mrope_section)[:-1].tolist()` and that will give you the split indices you need to get the equivalent MLX split.

**Comment by awni** [comment]
> I tried the MLX cumsum but I get an error ❌ :

Sorry we don't have int64 scans yet :\, let me make sure we have an issue to track that. For now you can do:

```
cu_seqlens = mx.cumsum(cu_seqlens.astype(mx.int32))
```

**Comment by Blaizzy** [comment]
Ohh, I see it now.

Thank you very much once again for the explanation! 

I should have plotted the tensor perhaps I would have e spotted the issue. It clear now that's why outputs didn't match with the transformers version.


The difference in Conv channel order between torch and MLX caught me good this time.

**Comment by Blaizzy** [comment]
> Oof using PyTorch in MLX code makes me a little sad 😢 .. you shouldn't need that. mx.split works like np.split which are both different than torch.split.
> 
> In short you can do mrope_section = np.cumsum(mrope_section)[:-1].tolist() and that will give you the split indices you need to get the equivalent MLX split.

This worked well :)

**Comment by Blaizzy** [comment]
> Sorry we don't have int64 scans yet :, let me make sure we have an issue to track that. For now you can do:
> cu_seqlens = mx.cumsum(cu_seqlens.astype(mx.int32))
This also worked well.

**Review by Blaizzy — COMMENTED** [review]
LGTM

**Comment by chigkim** [comment]
This is awesome!
Using --model mlx-community/Qwen2-VL-7B-Instruct-4bit throws an error about received parameters not in model. However, --model qwen/Qwen2-VL-7B-Instruct works.
It would be cool to be able to run 72B-4bit!
Also, does it work for video input?
Thanks!

**Comment by Blaizzy** [comment]
Will look into it tomorrow morning👌🏾

**Comment by Blaizzy** [comment]
Can you please share the error?

**Comment by Blaizzy** [comment]
You can run 72B-4bit 

I will share it tomorrow

**Comment by chigkim** [comment]
Sure!
```bash
python -m mlx_vlm.generate --model mlx-community/Qwen2-VL-7B-Instruct-4bit --max-tokens 100 --temp 0.0 --image boat.webp 
Fetching 11 files: 100%|████████████████████| 11/11 [00:00<00:00, 215595.07it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/generate.py", line 85, in <module>
    main()
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/generate.py", line 63, in main
    model, processor, image_processor, config = get_model_and_processors(args.model)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/generate.py", line 56, in get_model_and_processors
    model, processor = load(model_path, {"trust_remote_code": True})
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/utils.py", line 249, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/utils.py", line 215, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/cgk/Desktop/code/llm/mlx-vlm/.venv/lib/python3.12/site-packages/mlx/nn/layers/base.py", line 178, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: language_language_model.model.language_model.lm_head.scales language_language_model.model.language_model.lm_head.biases language_language_model.model.language_model.lm_head.weight.
```

Also, I get quite different description if I run with transformers.Qwen2VLForConditionalGeneration on my Mac.

boat

Transformers: The image depicts a serene lakeside scene surrounded by lush greenery. A small, red and green rowboat is dockeded on the shore of a calm lake. The boat is positioned near the edge of the water, with its bow facing the viewer. The lake is surrounded by dense trees and foliage, creating a tranquil and natural atmosphere. The sky above is partly cloudy, with patches of blue visible through the clouds. The reflection of the trees and sky on the water's surface adds to the peaceful ambiance of the scene.

Mlx-vlm: The image is a vertical panoramic view of a lush, green landscape. The scene is filled with a variety of plants, trees, and foliage, creating a dense and vibrant environment. The colors are predominantly green, with shades ranging from light to dark, indicating a rich diversity of plant life. The image appears to be taken from a high vantage point, possibly from a boat or a high vantage point on land, looking down onto the dense vegetation below. The overall impression is one of natural beauty

**Comment by arogister** [comment]
I was about to report the same issue about mlx-community/Qwen2-VL-7B-Instruct-8bit, here is the error thrown by mlx (0.18.0) :
mlx_vlm.generate --model mlx-community/Qwen2-VL-7B-Instruct-8bit --max-tokens 100             
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 166111.05it/s]
Traceback (most recent call last):
  File "/Users/arogister/Documents/mlx-vlm/.venv/bin/mlx_vlm.generate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/arogister/Documents/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/generate.py", line 63, in main
    model, processor, image_processor, config = get_model_and_processors(args.model)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arogister/Documents/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/generate.py", line 56, in get_model_and_processors
    model, processor = load(model_path, {"trust_remote_code": True})
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arogister/Documents/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/utils.py", line 249, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arogister/Documents/mlx-vlm/.venv/lib/python3.12/site-packages/mlx_vlm/utils.py", line 215, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/arogister/Documents/mlx-vlm/.venv/lib/python3.12/site-packages/mlx/nn/layers/base.py", line 178, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: language_language_model.model.language_model.lm_head.scales language_language_model.model.language_model.lm_head.weight language_language_model.model.language_model.lm_head.biases.

**Comment by arogister** [comment]
I also tested briefly this 2B model and got no error BUT the generated description is completely wrong, as if it was describing an entirely different image. I tried another one with same issue, then a third one that looked easy (cat picture) but the answer was : I'm sorry, but I can't assist with that.

python -m mlx_vlm.generate --model Qwen/Qwen2-VL-2B-Instruct --max-tokens 100 --temp 0.0 --image ../../../Pictures/20231008-DSCF0033.jpg 
Fetching 11 files: 100%|███████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 136098.36it/s]
==========
Image: ../../../Pictures/20231008-DSCF0033.jpg 

Prompt: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
<|vision_start|><|image_pad|><|vision_end|>What are these?<|im_end|>
<|im_start|>assistant

These are images of a river or a stream with green algae and floating debris. The water appears to be polluted, with a greenish-brown color and a layer of green algae on the surface. The image is likely taken from a boat or a drone, providing a bird's-eye view of the water body.
==========
Prompt: 0.572 tokens-per-sec
Generation: 21.719 tokens-per-sec

**Comment by Blaizzy** [comment]
My bad guys @MDR4356, @chigkim  and @arogister, I unintentionally introduced a bug in the vision module.

But it's fixed now, here is the PR #62.

**Comment by arogister** [comment]
Thanks, I confirm that this fixes both of the issues I reported (error + bad answer)!

**Comment by Blaizzy** [comment]
Awesome!

I'm in the process of releasing v0.1.0 :)

Introduce the trainer and fix a couple bugs I introduced yesterday.

**Comment by chigkim** [comment]
> You can run 72B-4bit

Where can I download 72B-4bit for mlx?

Also, non-instruct model keeps generating after <|endoftext|>. Is there a way to stop generating on the EOS token?

I can confirm #62 fixes the issues I mentioned. Thanks!

**Comment by ricced69** [comment]
Are there any updates on Qwen2-VL-72B? I can't find a download anywhere online.

**Comment by Blaizzy** [comment]
Uploading it right now :)

**Comment by ricced69** [comment]
That's awesome. Will this be in 4 bit? Also sorry for asking but I'm new here, where will you be uploading it?

**Comment by Blaizzy** [comment]
Still uploading but you can find it here:

https://huggingface.co/mlx-community/Qwen2-VL-72B-Instruct-4bit

**Pull request merged**
