### PR TITLE
Auto generated documentation

### PR DESCRIPTION
**Pull request by gabewillen**
You don't have to merge this. Just an example of auto generated documentation using AI. Unlike pasting code into chat-gpt or using copilot. This tool builds full dependency graphs and sends all the relevant code to the model in the context. It then injects the documentation into the parsed AST leaving the existing code untouched.

### CODE REVIEW

**Comment by gabewillen** [comment]
The entire process took two minutes

**Comment by gabewillen** [comment]
Want me to delete this PR?

**Comment by Blaizzy** [comment]
No, please keep it.

It's pretty interesting and I have lots of questions! 🔥

At the moment, I'm out on a trip and will get back to all your comments soon :)

If it's open-source we might merge it and have it as a default tool like gradio.

**Comment by Blaizzy** [comment]
> You don't have to merge this. Just an example of auto generated documentation using AI. Unlike pasting code into chat-gpt or using copilot. This tool builds full dependency graphs and sends all the relevant code to the model in the context. It then injects the documentation into the parsed AST leaving the existing code untouched.

I'm back,

@gabewillen this is impressive!

Where can I learn more about it?

**Comment by gabewillen** [comment]
Hey and thanks! I'm finishing it up now yours was only but a few I've ran it completely on. Soon it will actually create material ui mkdoc sites along with the documentation.

**Pull request closed without merging**
