### PR TITLE
Fix broken stream generate for SmolVLM and others

### PR DESCRIPTION
**Pull request by andimarafioti**
This breaks stream generation if the model doesn't have image_token_index

### CODE REVIEW

**Comment by Blaizzy** [comment]
Hey @andimarafioti 

Thanks for the PR!

To clarify, all models should have `image_token_index`.

I see that idefics3 uses instead `image_token_id`.

So the fix should be renaming it to `image_token_index`.

**Comment by Blaizzy** [comment]
Could you make the change above?

I will review and merge it as soon as you do.

**Comment by andimarafioti** [comment]
Why should the model have `image_token_index`? The idefics3 PR was reviewed quite intensely and no one mentioned this.

**Comment by andimarafioti** [comment]
Also, there is another part of this same file where this check is used to avoid other models failing :/

**Comment by Blaizzy** [comment]
> Why should the model have image_token_index? The idefics3 PR was reviewed quite intensely and no one mentioned this.

It was a mistake we all missed,

I also found another bug just now with the positioning of the image token from that PR.

**Comment by Blaizzy** [comment]
> Also, there is another part of this same file where this check is used to avoid other models failing :/

Ok, you have a point. I will re-open and merge your PR.

I'm about to refactor the entire codebase to address this cases because all model should have this even if it's zero/None.

**Comment by Blaizzy** [comment]
Thank you very much for bringing this up @andimarafioti!

**Pull request merged**
