### PR TITLE
Better error message for non safetensor repository

### LINKED ISSUE #14: FileNotFoundError: No safetensors found
Hello

I was trying out the `mlx-vlm` package and was able to run the default example [here](https://huggingface.co/mlx-community/llava-1.5-7b-4bit)

However, replacing the model card with [Efficient-Large-Model/VILA-13b-4bit-awq](https://huggingface.co/Efficient-Large-Model/VILA-13b-4bit-awq), it fails. heres the stack trace:

```
(mlx) shubham@Shubhams-MBP ~ % python -m mlx_vlm.generate --model Efficient-Large-Model/VILA-13b-4bit-awq \
--prompt "what are these?" --image "http://images.cocodataset.org/val2017/000000039769.jpg" \
--max-tokens 100 --temp 0.0

Fetching 7 files: 100%|████████████████████████| 7/7 [00:00<00:00, 14761.25it/s]
ERROR:root:No safetensors found in /Users/shubham/.cache/huggingface/hub/models--Efficient-Large-Model--VILA-13b-4bit-awq/snapshots/ab335be6c2a5b6a08d4784491bf270fe0ce7a41d
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/shubham/anaconda3/envs/mlx/lib/python3.12/site-packages/mlx_vlm/generate.py", line 107, in <module>
    main()
  File "/Users/shubham/anaconda3/envs/mlx/lib/python3.12/site-packages/mlx_vlm/generate.py", line 69, in main
    model, processor, image_processor, config = get_model_and_processors(args.model)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubham/anaconda3/envs/mlx/lib/python3.12/site-packages/mlx_vlm/generate.py", line 55, in get_model_and_processors
    model, processor = load(model_path, {"trust_remote_code": True})
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubham/anaconda3/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 212, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubham/anaconda3/envs/mlx/lib/python3.12/site-packages/mlx_vlm/utils.py", line 123, in load_model
    raise FileNotFoundError(f"No safetensors found in {model_path}")
FileNotFoundError: No safetensors found in /Users/shubham/.cache/huggingface/hub/models--Efficient-Large-Model--VILA-13b-4bit-awq/snapshots/ab335be6c2a5b6a08d4784491bf270fe0ce7a41d
(mlx) shubham@Shubhams-MBP ~ %
```

I am using a m1 MacBook Pro. Im new to `mlx-vlm` but im happy to work on this to add support.

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
- closes #14 
- added sample code in error message to show to create safetensors

### CODE REVIEW

**Comment by Blaizzy** [comment]
Thanks a lot! 

Let’s wait for the tests to clear.

**Comment by Blaizzy** [comment]
Could you change “local_id” to “local_dir”? 

After that we’ll merge it.

**Comment by Blaizzy** [comment]
Great, we are almost ready! 

Just missing the convert script after the last message.

**Comment by IamShubhamGupto** [comment]
> @IamShubhamGupto
> 
> Great, we are almost ready!
> 
> Just missing the convert script after the last message.

just added it, let me know if there are any more changes

**Comment by Blaizzy** [comment]
LGTM!

**Review by Blaizzy — APPROVED** [review]

**Comment by Blaizzy** [comment]
Thanks!

**Comment by Blaizzy** [comment]
@IamShubhamGupto What's your X account? 

I want to tag you on the next release :)

**Comment by IamShubhamGupto** [comment]
@Blaizzy haha thanks, sure my x account is `@iamshubhamgupto`

**Pull request merged**
