### PR TITLE
Update load_image function to handle BytesIO input

### PR DESCRIPTION
**Pull request by gabewillen**
The load_image function in mlx_vlm/utils.py is now updated to accept input as BytesIO representing base64 encoded images. This enhances the loading process by accommodating another type of input. Appropriate error handling has been added for potential IO errors.

### CODE REVIEW

**Comment by Blaizzy** [comment]
Hey @gabewillen 

Thanks for the great addition! 

Before I merge, could you run pre-commit?

**Comment by gabewillen** [comment]
> Hey @gabewillen
> 
> Thanks for the great addition!
> 
> Before I merge, could you run pre-commit to clear the tests?

Absolutely I got ahead of myself on the PR. Apologies I was in the process of following your CONTRIBUTION.md before you commented. It should be good to go now.

**Review by Blaizzy — APPROVED** [review]
LGTM!

**Comment by Blaizzy** [comment]
> Absolutely I got ahead of myself on the PR. Apologies I was in the process of following your CONTRIBUTION.md before you commented. It should be good to go now.

Any other changes you want to make before I merge ?

**Comment by Blaizzy** [comment]
Merged 👌🏽

Thank you for the contribution @gabewillen!

**Comment by gabewillen** [comment]
> > Absolutely I got ahead of myself on the PR. Apologies I was in the process of following your CONTRIBUTION.md before you commented. It should be good to go now.
> 
> Any other changes you want to make before I merge ?

Not right now but I plan to use this library for a fun project with my kids. Any additions I make I'll be glad to contribute. Excellent work on the library!

**Comment by Blaizzy** [comment]
It will be available on the next release.

**Comment by Blaizzy** [comment]
@gabewillen what’s your Twitter handle ?

**Comment by gabewillen** [comment]
> @gabewillen what’s your Twitter handle ?

I don't have a personal one but I do have one for a project I'm working on [https://x.com/StateforwardOrg](url)

**Comment by gabewillen** [comment]
I also have a tool I'm getting ready to release that builds dependency graphs of libraries and autogenerates mkdoc compatible documentation if you'd be interested I can run it on your project. It works really well.

**Comment by gabewillen** [comment]
It injects the documentation without modifying the source code

**Pull request merged**
