### PR TITLE
Fix Bugs in chat UI

### PR DESCRIPTION
**Pull request by terhechte**
The current version of the chat ui doesn't work because of wrong datatype assumptions. With these changes, running, e.g. Pixtral via `python -m mlx_vlm.chat_ui --model mlx-community/pixtral-12b-4bit` works again (on my system).

Llama vision still fails with a different error (`ValueError: `aspect_ratio_ids` must be provided if `pixel_values` is provided`) but Pixtral works.

### CODE REVIEW

**Comment by Blaizzy** [comment]
Thanks a lot @terhechte!

You can fix the llama-vision error by changing `utils.py` line 972 to:

```
kwargs = {
        k: v
        for k, v in zip(
            [
                "image_grid_thw",
                "image_sizes",
                "aspect_ratio_ids",
                "aspect_ratio_mask",
                "cross_attention_mask",
            ],
            inputs[3:],
        )
    }
```

**Comment by Blaizzy** [comment]
Could you run `pre-commit run --all` to fix the tests?

**Comment by terhechte** [comment]
Done

**Comment by Blaizzy** [comment]
Awesome! 

Could you please open an issue for the other bugs?

**Pull request merged**
