### PR TITLE
Trainer + Multi image v0.1.0

### LINKED ISSUE #73: Error running mlx-community/pixtral-12b-4bit
Hi, 

using this code trying to run "mlx-community/pixtral-12b-4bit" model:

```
import mlx.core as mx
from mlx_vlm import load, generate

model_path = "mlx-community/pixtral-12b-4bit"

model, processor = load(model_path)

prompt = processor.tokenizer.apply_chat_template(
    [{"role": "user", "content": f"<image>\nWhat are these?"}],
    tokenize=False,
    add_generation_prompt=True,
)

pic = "xxx.png"

output = generate(model, processor, pic, prompt, verbose=False)

print(output)
```

Getting following error: 

```
Traceback (most recent call last):
  File "/pixtral.py", line 8, in <module>
    model, processor = load(model_path)
                       ^^^^^^^^^^^^^^^^
  File "/mlx_vlm/utils.py", line 249, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx_vlm/utils.py", line 215, in load_model
    model.load_weights(list(weights.items()))
  File "/mlx/nn/layers/base.py", line 178, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: vision_tower.vision_model.vision_model.transformer.layers.16.feed_forward.down_proj.weight vision_tower.vision_model.vision_model.transformer.layers.12.attention.q_proj.biases vision_tower.vision_model.vision_model.transformer.layers.22.attention.k_proj.scales vision_tower.vision_model.vision_model.transformer.layers.19.attention.v_proj.weight 
....
```

Anyone a solution? 

Thanks.

### PR DESCRIPTION
**Pull request by Blaizzy**
This PR adds:
- LoRA and QLoRA fine-tuning 
- Multi-image support 
- Batch processing
- image resizing

New Models
- Pixtral
- Qwen2-VL
- Llava-Interleave

Closes #73, #69

### CODE REVIEW

**Comment by lin72h** [comment]
It's happening!

**Comment by Blaizzy** [comment]
Absolutely! 🚀

**Comment by yukiarimo** [comment]
Any updates? Is it usable?

**Comment by Blaizzy** [comment]
Hey @yukiarimo 

It's almost done. 

I just want to run some extra tests (QLoRA, full finetune) and finish Qwen2-VL to release it.

**Comment by ndanielsen** [comment]
is there a dataset/ script that I can test this with my mac studio?

**Pull request merged**
