### PR TITLE
Added: Qwen2-VL Unit Tests, Refactored Weight Sanitization

### PR DESCRIPTION
**Pull request by benzimring**
The prefix issue was resolved, however creating PR with the logic refactored as requested by @Blaizzy in https://github.com/Blaizzy/mlx-vlm/issues/61

### CODE REVIEW

**Comment by Blaizzy** [comment]
The base branch has to be `main` and not `pc/tuner`.

And also, can you check this change with all model from the `qwen`(full precision) and `mlx-community` (quants) repo.

**Comment by benzimring** [comment]
Yep, realized that quickly 😆

To clarify, should the checks be added in the form of unit tests with those configurations?

**Comment by benzimring** [comment]
I can confirm Qwen models succeed with these changes, however inference with quantized versions from mlx-community error as mentioned in https://github.com/Blaizzy/mlx-vlm/pull/64

```
% python -m mlx_vlm.generate --model mlx-community/Qwen2-VL-2B-4bit --max-tokens 100 --temp 0.0

Traceback (most recent call last):
  <.....>
  logits = model(input_ids, pixel_values, cache=cache, mask=mask, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benzimring/mlx-vlm/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 94, in __call__
  input_embddings = self.get_input_embeddings(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benzimring/mlx-vlm/mlx_vlm/models/qwen2_vl/qwen2_vl.py", line 57, in get_input_embeddings
  inputs_embeds = self.language_model.model.embed_tokens(input_ids)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benzimring/mlx-vlm/.venv/lib/python3.12/site-packages/mlx/nn/layers/quantized.py", line 97, in __call__
  self["weight"][x],
  ~~~~~~~~~~~~~~^^^
ValueError: [gather] Got indices with invalid dtype. Indices must be integral.
```

This appears to be a separate issue however.

**Comment by Blaizzy** [comment]
Awesome, great job!

**Comment by Blaizzy** [comment]
> To clarify, should the checks be added in the form of unit tests with those configurations?

Unit tests

**Comment by benzimring** [comment]
Alright, I'll go ahead and add unit tests for qwen2-vl too then unless this is already being worked on?

**Comment by Blaizzy** [comment]
You can go ahead!

Btw, I will need your help reviewing #41 or fixing bugs after merge I anticipate some breaking changes.

**Comment by benzimring** [comment]
- Unit tests were added for Qwen2-VL, using HF's [`https://test_modeling_qwen2_vl.py`](https://github.com/huggingface/transformers/blob/570c89625b329a2d33ecbfb972a9aae015535471/tests/models/qwen2_vl/test_modeling_qwen2_vl.py) as a lightweight config reference.
- `mrope` config validation was added to the Language model
- the vision test runner was updated to assert that the size of the vision layer's outputs is as expected.

**Comment by Blaizzy** [comment]
This is awesome! 

Can we create a models/unit folder in the tests for this model specific tests.

**Comment by Blaizzy** [comment]
Thanks a lot @benzimring!

**Pull request merged**
